In [1]:
import pandas as pd

In [13]:
sentence_data = pd.read_csv("data/sentence_data.csv")
matches = pd.read_csv("data/all_sent_data.csv")
sentence_data.columns = ["index", "file", "sentence"]
matches.sort_values("sent_nums")

        Unnamed: 0  sent_nums total_hits
9109          9109          2    [80879]
14389        14389          2   [226229]
17087        17087          2   [156118]
147152      147152          2   [172701]
29608        29608          2     [6625]
...            ...        ...        ...
89074        89074     737140   [733891]
216278      216278     737140   [727385]
168387      168387     737140   [704943]
172022      172022     737140   [715426]
219908      219908     737140   [680793]

[306033 rows x 3 columns]

In [27]:
hits = matches.total_hits.tolist()
original_sent = matches.sent_nums.tolist()
all_sents = sentence_data.index.tolist()
sentences = sentence_data.sentence.tolist()

306033

In [ ]:
final_hits = []
y=0
for sent in all_sents:
    if y % 1000 == 0:
        print (y)
    x=0
    total_hits = []
    for sent_num in original_sent:
        if sent_num == sent:
            hit = hits[x]
            hit = int(hit.replace("[", "").replace("]", ""))
            
            total_hits.append(sentences[hit])
        x=x+1
    if len(total_hits) > 0:
        final_hits.append(total_hits)
    else:
        final_hits.append(0)
    y=y+1

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000
128000
129000
130000
131000
132000
133000
134000
135000
136000
137000
138000
139000
140000
141000
142000
143000
144000
145000
146000
147000
148000
149000
150000
151000
152000
153000
154000
155000
156000
157000
158000
159000
160000
161000
162000
163000
164000
165000
166000
167000
168000
169000
170000
171000
172000
173000
174000
175000
176000
177000
178000
179000
180000
181000
182000
183000
184000
185000
186000
187000
188000
189000
190000
191000
192000
193000
194000
195000
196000
197000
198000
199000
200000
201000
202000
203000
204000
205000
206000
207000
208000
209000
210000
211000
212000
213000
214000
215000
216000
217000
218000

In [31]:
# final_hits

In [ ]:
sentence_data["matches"] = final_hits

In [ ]:
sentence_data

In [ ]:
sentence_data.to_csv("data/complete_data.csv")